PetSitting/Controllers/SittersController.cs
namespace PetSitting.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Web.Mvc;
    using PetSitting.BusinessLogic;
    using PetSitting.Common;
    using PetSitting.Model;
    using PagedList;
    public class SittersController : Controller
    {
        private LoggingHandler _loggingHandler;

        public SittersController()
        {
            _loggingHandler = new LoggingHandler();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_loggingHandler != null)
                {
                    _loggingHandler.Dispose();
                    _loggingHandler = null;
                }
            }

            base.Dispose(disposing);
        }

        // GET: Sitters/Select
        [PetSitting.MvcApplication.MustBeLoggedIn]
        public ActionResult SelectSitter()
        {
                var sitters = from e in ListAllSitters()
                              orderby e.SitterID
                              select e;
                return View(sitters);
        }
        [PetSitting.MvcApplication.MustBeLoggedIn]
        public ActionResult Choose(int id, decimal fee)
        {
            try
            {
                Session["ChosenSitterID"] = id;
                Session["ChosenSitterFee"] = fee;
                return RedirectToAction("../Sessions/CreateByOwner/" + Session["ChosenOwnerID"]);

            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }
        [PetSitting.MvcApplication.MustBeLoggedIn]
        public ActionResult Chosen(int id, decimal fee)
        {
            
            Session["ChosenSitterID"] = id;
            Session["ChosenSitterFee"] = fee;
            return RedirectToAction("../Sessions/CreateByOwner/" + Session["AUTHOwnerID"]);
        }
        // GET: Sitters
        public ActionResult Index()
        {
            if ((string)Session["AUTHRole"] == null)
            {
                return RedirectToAction("../Home/Login");
            }
            return View();
        }

        // GET: Sitters/Details/5
        [PetSitting.MvcApplication.MustBeLoggedIn]
        public ActionResult Details(int id)
        {
            try
            {
                var sitter = SelectSitterById(id);
                return View(sitter);
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }

        // GET: Sitters/Create
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sitters/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult Create(FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                InsertSitter(collection["Name"],
                                int.Parse(collection["Age"]),
                                decimal.Parse(collection["Fee"]),
                                collection["Bio"],
                                collection["HiringDate"].Trim().Length == 0
                                ? (DateTime?)null
                                : DateTime.ParseExact(collection["HiringDate"], "MM/dd/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None),
                                decimal.Parse(collection["GrossSalary"]));

                return RedirectToAction("ListAll");
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }

        // GET: Sitters/Edit/5
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin,Sitter")]
        public ActionResult Edit(int id)
        {
            try
            {
                var sitter = SelectSitterById(id);
                return View(sitter);
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }

        // POST: Sitters/Edit/5
        [HttpPost]
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin,Sitter")]
        public ActionResult Edit(int id, FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                UpdateSitter(int.Parse(collection["SitterID"]),
                                collection["Name"],
                                int.Parse(collection["Age"]),
                                decimal.Parse(collection["Fee"]),
                                collection["Bio"],
                                collection["HiringDate"].Trim().Length == 0
                                ? (DateTime?)null
                                : DateTime.ParseExact(collection["HiringDate"], "MM/dd/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None),
                                decimal.Parse(collection["GrossSalary"]), 
                                collection["Email"],
                                collection["Username"],
                                collection["FirstName"],
                                collection["LastName"],
                                collection["Password"],
                                collection["Role"]);

                if ((string)Session["AUTHRole"] == "Admin")
                {
                    return RedirectToAction("ListAll");
                }
                else if ((string)Session["AUTHRole"] == "Sitter")
                {
                    return RedirectToAction("../Sitters/Details/" + collection["SitterID"]);
                }
                return View();
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }

        // GET: Sitters/Delete/5
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                var sitter = SelectSitterById(id);
                return View(sitter);
                
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }

        // POST: Sitters/Delete/5
        [HttpPost]
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                DeleteSitter(id);

                return RedirectToAction("ListAll");
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult ListAll(string Sorting_Order, int? page)
        {
            try
            {
                ViewBag.CurrentSort = Sorting_Order;
                ViewBag.SortingSitterName = String.IsNullOrEmpty(Sorting_Order) ? "SitterNameDESC" : "";
                ViewBag.SortingSitterName = Sorting_Order == "SitterNameDESC" ? "SitterNameASC" : "SitterNameDESC";
                ViewBag.SortingFee = Sorting_Order == "FeeDESC" ? "FeeASC" : "FeeDESC";
                ViewBag.SortingAge = Sorting_Order == "AgeDESC" ? "AgeASC" : "AgeDESC";
                ViewBag.SortingHiringDate = Sorting_Order == "HiringDateDESC" ? "HiringDateASC" : "HiringDateDESC";
                ViewBag.SortingGrossSalary = Sorting_Order == "GrossSalaryDESC" ? "GrossSalaryASC" : "GrossSalaryDESC";
                ViewBag.SortingNetSalary = Sorting_Order == "NetSalaryDESC" ? "NetSalaryASC" : "NetSalaryDESC";
                ViewBag.SortingModifiedDate = Sorting_Order == "ModifiedDateDESC" ? "ModifiedDateASC" : "ModifiedDateDESC";
                ViewBag.SortingTotalSales = Sorting_Order == "TotalSalesDESC" ? "TotalSalesASC" : "TotalSalesDESC";
                ViewBag.SortingSessionsCount = Sorting_Order == "SessionsCountDESC" ? "SessionsCountASC" : "SessionsCountDESC";
                var sitters = from e in ListAllSitters() select e;
                switch (Sorting_Order)
                {
                    case "TotalSalesASC":
                        sitters = sitters.OrderBy(e => e.TotalSales);

PetSitting/Views/Owners/Create.cshtml
@model PetSitting.Model.OwnersEntity

@{
    ViewBag.Title = "Create";
}

<div class="panel"><div class="panel-heading"><h3>Create Owner</h3></div>
<div class="panel-body">

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control", @style = "display: none;", @Value = "Owner" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListAll")
</div>
</div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetSitting/Views/Owners/Delete.cshtml
@model PetSitting.Model.OwnersEntity

@{
    ViewBag.Title = "Delete";
}

<div class="panel"><div class="panel-heading"><h3>Delete</h3></div>
<div class="panel-body">
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OwnersEntity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OwnerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetYears)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetYears)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-warning" /> |
            @Html.ActionLink("Back to List", "ListAll")
        </div>
    }
</div>
</div>
</div>

PetSitting/Views/Owners/Details.cshtml
@model PetSitting.Model.OwnersEntity

@{
    ViewBag.Title = "Details";
}

<div class="panel">
    <div class="panel-heading"><h3>Owner Details</h3></div>
    <div class="panel-body">
        <div>
            @Html.ActionLink("Edit", "Edit", new { id = Model.OwnerID })

            <dl class="dl-horizontal">


                <dd class="lead">
                    @Html.DisplayFor(model => model.OwnerName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Username)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Username)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Age)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Age)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.PetName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PetName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PetAge)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PetAge)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PetYears)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PetYears)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ContactPhone)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ContactPhone)
                </dd>

                <dd>
                    <br /><br />
                    @{ if ((string)Session["AUTHRole"] != "Admin")
                        {
                            @Html.ActionLink("Request Session", "SelectSitter", "Sitters")
                        }

                    }

                    <br /><br />
                    @Html.DisplayFor(model => model.Sessions, "SessionsByOwner")
                </dd>
            </dl>
        </div>
        <p>
            @{ if ((string)Session["AUTHRole"] == "Admin")
                {
                    <b>|</b>
                    @Html.ActionLink("Back to List", "ListAll");
                }
            }
        </p>
        <p>Details last modified: @Html.DisplayFor(model => model.ModifiedDate)</p>
    </div>
</div>

PetSitting/Views/Owners/Edit.cshtml
@model PetSitting.Model.OwnersEntity

@{
    ViewBag.Title = "Edit";
}

<div class="panel"><div class="panel-heading"><h3>Owner Edit</h3></div>
<div class="panel-body">

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.OwnerID, new { style = "display: none;", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactPhone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control", @style = "display: none;" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @{ var sessionrole = Session["AUTHRole"] as string;
        if (sessionrole == "Admin")
        {
            @Html.ActionLink("Back to List", "ListAll")
        }

    }
</div>
</div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetSitting/Views/Owners/ListAll.cshtml
@model PagedList.IPagedList<PetSitting.Model.OwnersEntity>
@using PagedList.Mvc;

@{
    ViewBag.Title = "ListAll";
}

<div class="panel">
    <div class="panel-heading"><h3>Owners</h3></div>
    <div class="panel-body">
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.ActionLink("Owner Name", "ListAll", new { Sorting_Order = ViewBag.SortingOwnerName })
                </th>
                <th>
                    @Html.ActionLink("Pet Name", "ListAll", new { Sorting_Order = ViewBag.SortingPetName })
                </th>
                <th>
                    @Html.ActionLink("Pet Age", "ListAll", new { Sorting_Order = ViewBag.SortingPetAge })
                </th>
                <th>
                    @Html.ActionLink("Pet Years", "ListAll", new { Sorting_Order = ViewBag.SortingPetYears })
                </th>
                <th>
                    @Html.ActionLink("Contact Phone", "ListAll", new { Sorting_Order = ViewBag.SortingContactPhone })
                </th>
                <th>
                    @Html.ActionLink("Sessions Count", "ListAll", new { Sorting_Order = ViewBag.SortingSessionsCount })
                </th>
                <th>
                    @Html.ActionLink("Total Sales", "ListAll", new { Sorting_Order = ViewBag.SortingTotalSales })
                </th>
                <th>
                    @Html.ActionLink("Modified Date", "ListAll", new { Sorting_Order = ViewBag.SortingModifiedDate })
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OwnerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PetName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PetAge)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PetYears)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContactPhone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SessionsCount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalSales)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedDate)
                    </td>
                    <td>
                        @{ if ((string)Session["AUTHRole"] == "Admin")
                            {
                                @Html.ActionLink("Choose", "Choose", new { @id = item.OwnerID }) <text> | </text>
                            }
                        }
                        @Html.ActionLink("Edit", "Edit", new { id = item.OwnerID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.OwnerID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.OwnerID })
                    </td>
                </tr>
            }

        </table>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("ListAll", new { page, Sorting_Order = ViewBag.CurrentSort }))

    </div>
</div>