PetSitting/Controllers/OwnersController.cs
namespace PetSitting.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using PetSitting.BusinessLogic;
    using PetSitting.Common;
    using PetSitting.Model;
    using PagedList;
    public class OwnersController : Controller
    {
        private LoggingHandler _loggingHandler;

        public OwnersController()
        {
            _loggingHandler = new LoggingHandler();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_loggingHandler != null)
                {
                    _loggingHandler.Dispose();
                    _loggingHandler = null;
                }
            }

            base.Dispose(disposing);
        }

        // GET: Owners
        public ActionResult Index()
        {
            return View();
        }

        // GET: Owners/Choose
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult Choose(int id)
        {
            try
            {
                Session["ChosenOwnerID"] = id;
                return RedirectToAction("../Sitters/ListAll");
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }
        // GET: Owners/Details/5
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin,Owner")]
        public ActionResult Details(int id)
        {
            try
            {
                var owner = SelectOwnerById(id);
                return View(owner);
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }
        
        // GET: Owners/Create
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Owners/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult Create(FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                InsertOwner(collection["OwnerName"],
                                collection["PetName"],
                                int.Parse(collection["PetAge"]),
                                collection["ContactPhone"],
                                collection["FirstName"],
                                collection["LastName"],
                                collection["Username"],
                                collection["Password"],
                                int.Parse(collection["Age"]),
                                collection["Email"],
                                collection["Role"]);

                return RedirectToAction("ListAll");
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }

        // GET: Owners/Edit/5
        [PetSitting.MvcApplication.MustBeLoggedIn]
        public ActionResult Edit(int id)
        {
            try
            {
                var owner = SelectOwnerById(id);
                return View(owner);
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }

        // POST: Owners/Edit/5
        [HttpPost]
        [PetSitting.MvcApplication.MustBeLoggedIn]
        public ActionResult Edit(int id, FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                UpdateOwner(int.Parse(collection["OwnerID"]),
                                collection["OwnerName"],
                                collection["PetName"],
                                int.Parse(collection["PetAge"]),
                                collection["ContactPhone"],
                                collection["FirstName"],
                                collection["LastName"],
                                collection["Username"],
                                collection["Password"],
                                int.Parse(collection["Age"]),
                                collection["Email"],
                                collection["Role"]);

                if ((string)Session["AUTHRole"] == "Admin")
                {
                    return RedirectToAction("ListAll");
                }
                else if ((string)Session["AUTHRole"] == "Owner")
                {
                    return RedirectToAction("../Owners/Details/" + collection["OwnerID"]);
                }
                return View();

            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }

        // GET: Owners/Delete/5
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                var owner = SelectOwnerById(id);
                return View(owner);
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }

        // POST: Owners/Delete/5
        [HttpPost]
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                DeleteOwner(id);

                return RedirectToAction("ListAll");
            }
            catch (Exception ex)
            {
                //Log exception error
                _loggingHandler.LogEntry(ExceptionHandler.GetExceptionMessageFormatted(ex), true);
                ViewBag.Message = Server.HtmlEncode(ex.Message);
                return View("Error");
            }
        }
        [PetSitting.MvcApplication.MustBeInRole(Roles="Admin")]
        public ActionResult ListAll(string Sorting_Order, int? page)
        {
            try
            {
                ViewBag.CurrentSort = Sorting_Order;
                ViewBag.SortingOwnerName = String.IsNullOrEmpty(Sorting_Order) ? "OwnerNameDESC" : "";
                ViewBag.SortingOwnerName = Sorting_Order == "OwnerNameDESC" ? "OwnerNameASC" : "OwnerNameDESC";
                ViewBag.SortingPetName = Sorting_Order == "PetNameDESC" ? "PetNameASC" : "PetNameDESC";
                ViewBag.SortingPetAge = Sorting_Order == "PetAgeDESC" ? "PetAgeASC" : "PetAgeDESC";
                ViewBag.SortingPetYears = Sorting_Order == "PetYearsDESC" ? "PetYearsASC" : "PetYearsDESC";
                ViewBag.SortingContactPhone = Sorting_Order == "ContactPhoneDESC" ? "ContactPhoneASC" : "ContactPhoneDESC";
                ViewBag.SortingModifiedDate = Sorting_Order == "ModifiedDateDESC" ? "ModifiedDateASC" : "ModifiedDateDESC";
                ViewBag.SortingSessionsCount = Sorting_Order == "SessionsCountDESC" ? "SessionsCountASC" : "SessionsCountDESC";
                ViewBag.SortingTotalSales = Sorting_Order == "TotalSalesDESC" ? "TotalSalesASC" : "TotalSalesDESC";
                var owners = from e in ListAllOwners() select e;
                switch (Sorting_Order)
                {
                    case "SessionsCountASC":
                        owners = owners.OrderBy(e => e.SessionsCount);
                        break;
                    case "SessionsCountDESC":
                        owners = owners.OrderByDescending(e => e.SessionsCount);
                        break;
                    case "TotalSalesASC":
                        owners = owners.OrderBy(e => e.TotalSales);
                        break;
                    case "TotalSalesDESC":
                        owners = owners.OrderByDescending(e => e.TotalSales);
                        break;
                    case "OwnerNameASC":
                        owners = owners.OrderBy(e => e.OwnerName);
                        break;
                    case "OwnerNameDESC":
                        owners = owners.OrderByDescending(e => e.OwnerName);
                        break;
                    case "PetNameASC":
                        owners = owners.OrderBy(e => e.PetName);
                        break;
                    case "PetNameDESC":
                        owners = owners.OrderByDescending(e => e.PetName);
                        break;
                    case "PetAgeASC":
                        owners = owners.OrderBy(e => e.PetAge);
                        break;
                    case "PetAgeDESC":
                        owners = owners.OrderByDescending(e => e.PetAge);
                        break;

PetSitting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Calvin's Pet Sitting</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-image: linear-gradient(to bottom right, brown, green);">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @{ var sessionrole = Session["AUTHRole"] as string;
                        var sessionuserid = Session["AUTHUserID"] as int?;
                        if (sessionrole == "Owner")
                        {
                            <li>@Html.ActionLink("Owner Details", "Details", "Owners", new { @id = (int)Session["AUTHOwnerID"] }, null)</li>
                        }
                        else if (sessionrole == "Sitter")
                        {
                            <li>@Html.ActionLink("Sitter Details", "Details", "Sitters", new { @id = (int)Session["AUTHSitterID"] }, null)</li>
                        }
                        else if (sessionrole == "Admin")
                        {
                            <li>@Html.ActionLink("Owners", "ListAll", "Owners")</li>
                            <li>@Html.ActionLink("Sitters", "ListAll", "Sitters")</li>
                            <li>@Html.ActionLink("Users", "ListAll", "Users")</li>
                            <li>@Html.ActionLink("Sessions", "ListAll", "Sessions")</li>
                        }
                        if (sessionrole != null)
                        {
                            <li class="right">@Html.ActionLink("Log out", "Logout", "Home")</li>
                        }
                    }


                </ul>
            </div>
        </div>
    </div> 
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Calvin's Pet Sitting</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>